### ISSUE TITLE
Fix reusable describe action

### ISSUE THREAD

**Issue by FyzHsn** [AgnostiqHQ/covalent#1543]
### Environment

- **Covalent version**: 0.218.0rc0
- **Python version**: 3.8.13
- **Operating system**: MacOS

### What is happening?

The current implementation of the `describe` action does not seem to be compatible with the Executor plugin repos. So far, we have been replicating the changelog in each repo which makes it more difficult to maintain in the long run. The current implementation of the describe action gives the following error:

```
Branch history is not linear. Try squashing your commits.
```

Furthermore, when the changelog fails, it doesn't produce a new tag successfully as a result of which the test workflow also fails with error shown below.

The step that fails is:

```
Run actions-ecosystem/action-get-latest-tag@v1
  with:
    semver_only: true
    initial_version: v0.0.0
    with_initial_version: true
```

The error msg is: 

```
fatal: could not read Username for 'https://github.com/': No such device or address
```

### How can we reproduce the issue?

Use the following `changelog.yml` in any of the executor plugin repos which uses the actions in the Covalent repo:

```
name: changelog

on: 
  pull_request:
  push:
    branches:
      - develop
    paths-ignore:
      - 'CHANGELOG.md'
      - 'VERSION'

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      index: ${{ steps.filter.outputs.index }}
      action: ${{ steps.filter.outputs.action }}
      dist: ${{ steps.filter.outputs.dist }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - name: Check out head
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COVALENT_OPS_BOT_TOKEN }}

      - name: Latest tag
        id: get-latest-tag
        uses: AgnostiqHQ/covalent/.github/actions/describe@develop
        with:
          token: ${{ secrets.COVALENT_OPS_BOT_TOKEN }}
          branch: develop
          stable: false

      - name: Update version number
        id: changelog
        uses: AgnostiqHQ/covalent/.github/actions/changelog@develop
        with:
          changelog-path: CHANGELOG.md
          version-path: VERSION
          token: ${{ secrets.COVALENT_OPS_BOT_TOKEN }}
          basehead: ${{ steps.get-latest-tag.outputs.tag }}...${{ github.sha }}

      - name: Commit
        if: ${{ steps.changelog.outputs.message != 'noop' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CovalentOpsBot
          author_email: covalentopsbot@users.noreply.github.com
          message: ${{ steps.changelog.outputs.message }}
          push: origin develop --force

  action-build:
    needs: changelog
    if: >-
      ${{ (needs.changelog.outputs.action == 'true' || needs.changelog.outputs.index == 'true')
      && needs.changelog.outputs.dist == 'false' }}
    uses: AgnostiqHQ/covalent/.github/workflows/action_build.yml@develop
    secrets: inherit # pragma: allowlist secret
```

### What should happen?

Instead of the changelog workflow failing with the error above after it is merged to develop, it should properly update the version.

Furthermore, the test action should also pass. 

### Any suggestions?

To fix the describe action:

```
  while (latestTag == null) {
    i = 0;
    while (i < tags.length && latestTag == null) {
      if (
        commit === tags[i].commit.sha &&
        (!tags[i].name.match("rc") || !stable) &&
        tags[i].name.match(re)
      )
        latestTag = tags[i].name;
      i++;
    }
    if (latestTag == null) {
      const { data: data } = await octokit.rest.repos.getCommit({
        owner: owner,
        repo: repo,
        ref: commit,
      });
      if (data.parents.length !== 1) {
        core.setFailed(
          "Branch history is not linear. Try squashing your commits."
        );
        return;
      } else {
        commit = data.parents[0].sha;
      }
    }
  }
  if (latestTag == null) {
    core.setFailed(
      "The action couldn't find a matching recent tag. Did you create your branch from a release tag?"
    );
    return;
  } else {
    core.setOutput("tag", latestTag);
  }
};
```

we might have to alter the logic in the following snippet:

```
      if (data.parents.length !== 1) {
        core.setFailed(
          "Branch history is not linear. Try squashing your commits."
        );
```

When PR's get merged the commit often have two parents. The describe action here is failing at the step that checks that the commit action has 1 parent in which case it does not. One solution could be to replace this logic with a function called recursively so that it traverses the entire commit tree including the case where the commit has multiple parents.
